# mandatory configuration
QENGINE_CACHE_DIR: 
QENGINE_SALT: must_be_16_24_or_32_chars_long__

# optional configuration
QENGINE_IV: must_be_16_long_
QENGINE_LOG_REQUESTS: False
QENGINE_MOOLE_HACKS: False
QENGINE_NO_CACHE: True
QENGINE_PASSKEY: 

# engine info
ENGINEINFO_name: 

# urls to block containers
# PYTHON2_URL: 
# SAGE_URL: 
